### ISSUE TITLE
Not able to run without sudo even after using udev rules

### ISSUE THREAD

**Issue by gits00** [darrylb123/usbrelay#101]
Tried - 

$ sudo cp 50-usbrelay.rules /etc/udev/rules.d
$ sudo udevadm control -R
The command after that - 
sudo usermod -a -G usbrelay <user name>
didn't work.
Gives error - usermod: group 'usbrelay' does not exist
How to add the usbrelay group?

Output -

python3 usbrelay_test.py 

/dev/hidraw4: Permission denied
Unable to open any device - Use root, sudo or set the device permissions via udev
Count:  1
Boards:  (('', 8, 0),)
Board:  ('', 8, 0)
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1
operate_relay() Unable to write or unknown relay
Error: (null)
Result:  -1

 usbrelay 
/dev/hidraw4: Permission denied
Unable to open any device - Use root, sudo or set the device permissions via udev

I am using Ubuntu 18.04.5 LTS

**Comment by darrylb123** [comment]
If you are using Ubuntu or debian substitute the group plugdev for usbrelay.

Darryl

**Comment by darrylb123** [comment]
Note I've updated the README to show this.

**Comment by gits00** [comment]
Thanks! This worked.
