### ISSUE TITLE
Add support for paho.mqtt.python 2.0+

### ISSUE THREAD

**Issue by nullr0ute** [darrylb123/usbrelay#111]
There's breaking changes for paho.mqtt.python 2.0 and later so it would be useful to be able to use the later releases, in particular in distros.

https://github.com/eclipse/paho.mqtt.python/releases/tag/v2.0.0

**Comment by wentasah** [comment]
#112 should do, what's necessary.

**Comment by darrylb123** [comment]
Indeed will.
