### ISSUE TITLE
How to get it working in javascript under Windows environment using serialport

### ISSUE THREAD

**Issue by Ryebreadizzle** [darrylb123/usbrelay#16]
I apologize for this is not an issue but the only way I found I could reach you. I have the 2 channel usb relay module and have established a connection with it in javascript but don't know the commands to make it work. I have bought a similar usb relay module (a one channel module) that can be found here: https://goo.gl/a04gvL and have gotten it to work in a similar fashion: Establishing a serial port connection and writing to the port given the instructions. However I have found no such instructions for this device. Would you help me out?

**Comment by darrylb123** [comment]
I wouldn't know where to start. The device uses the hid protocol.
Why not use the supplied windows c libraries and write a wrapper to call
from JavaScript.

Darryl

**Comment by Ryebreadizzle** [comment]
Thanks for the quick response! How exactly would I go about doing that: I am fairly new to this level of programming. Is there a tutorial or such that could assist me?

Ryebread

**Comment by darrylb123** [comment]
Sorry, I'm an old school Linux C programmer. Not familiar with Windows or
JavaScript programming. I suggest Google is your friend.

**Comment by Ryebreadizzle** [comment]
Okay, thanks for your quick replies.
