### ISSUE TITLE
no output on orange pi zero

### ISSUE THREAD

**Issue by ChrisVonFrosta** [darrylb123/usbrelay#31]
Hi,
i installed usbrelay programm(SW) with apt-get. Using it make no error but also no output.
The usb relay is connected, works well on Raspberry with this SW.

I tried to compile from source... needed to install hidapi and hidapi_dev, make and, GCC.
Now, "make Makefile install"  runs without error.
But the SW give still no output.
Any Idea?

**Comment by ChrisVonFrosta** [comment]
I change to 
´´´HIDAPI = libusb ```
in Makefile. It works then!
thank you !

**Comment by darrylb123** [comment]
Thanks for working it out yourself. I don't have a pi zero.

Regards
Darryl
