### ISSUE TITLE
Activate All Relays

### ISSUE THREAD

**Issue by thunkableBob** [darrylb123/usbrelay#57]
What is the entry to enable all relays at once?
I have tried relay_9=1  and relay_0=1.  (0 changes serial to 1).
I changed serial from 6QMBS to relay.
I can successfully activate each relay, but need to activate all at once.

**Comment by darrylb123** [comment]
Should be possible, let me look into it.

**Comment by darrylb123** [comment]
What about putting them all on the one command line, does that operated
close enough together?

**Comment by darrylb123** [comment]
Added the mythical relay 9 to operate all relays at once. Works the same way as the ucreate relay modules.
Relay 9 is the same, regardless of the number of relays.

**Comment by thunkableBob** [comment]
Thanks for that, Darryl.
This problem shows on a laptop using Linux Mint 19.3. Even in a command
line, the relays activate individually.
When I run it on Ubuntu 20.04 in Python 3, if I put all in a command line,
then those relays activate at the same time.

**Comment by darrylb123** [comment]
So you are using the python library. That's cool, the relay 9 change should
work fine in python too.
