### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by kcgitlb** [darrylb123/usbrelay#59]
When I run usbrelay command , it gives following memory error,
$ sudo usbrelay
free(): invalid next size (fast)
Aborted

**Comment by darrylb123** [comment]
Please run the command with -d to confirm the executable and library is in
sync.

**Comment by kcgitlb** [comment]
Still gives same error (at last line), and can't change state

> $ sudo usbrelay -d
> Found 1 devices
> Device Found
>  type: 16c0 05df
>   path: /dev/hidraw0
>   serial_number: KC1MB

> 
> Manufacturer: www.dcttech.com
>   Product:      USBRelay1
>   Release:      100
>   Interface:    0
>   Number of Relays = 1
>   Module_type = 1
> KC1MB_1=0
> Device Found
>   type: 16c0 05df
>   path: /dev/hidraw1
>   serial_number: KC1PW
> Manufacturer: www.dcttech.com
>   Product:      USBRelay1
>   Release:      100
>   Interface:    
> 
> 
>   Number of Relays = 1
>   Module_type = 1
> KC1PW_1=0
> **free(): invalid next size (fast)
> Aborted**

**Comment by kcgitlb** [comment]
It's fixed when connected relays to different ports.

**Comment by darrylb123** [comment]
Looks like an old version too. Can you clone and build the latest version
and try again on both the dodgy port and a working port. See the readme for
how to build it from source.

Darryl
