### ISSUE TITLE
please specify a proper license to make this distributable

### ISSUE THREAD

**Issue by jandd** [darrylb123/usbrelay#6]
I would like to package usbrelay for Debian. Please specify the license terms of your code in a license file, because your code is not distributable without explicitly expressed license terms. I suggest to use one of the popular [OSI aproved licenses](http://opensource.org/licenses).

**Comment by darrylb123** [comment]
Jan,
The package currently available for raspian does not work.
The github code compiles and works fine. I think the dependencies have changed.

**Comment by jandd** [comment]
@darrylb123 does raspian use the original Debian package or do they rebuild the package

**Comment by darrylb123** [comment]
I don't know. Does the debian jessie work?

Here is the result of apt-cache depends on Raspian Jessie

$ sudo apt-cache depends usbrelay

usbrelay

  Depends: libc6

  Depends: libhidapi-hidraw0


Here is the results of my compiled binary

$ ldd usbrelay

/usr/lib/arm-linux-gnueabihf/libarmmem.so (0xb6f6c000)

libhidapi-hidraw.so.0 => /usr/lib/arm-linux-gnueabihf/libhidapi-hidraw.so.0
(0xb6f4b000)

libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb6e0a000)

libudev.so.1 => /lib/arm-linux-gnueabihf/libudev.so.1 (0xb6ded000)

/lib/ld-linux-armhf.so.3 (0x7f610000)

librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6dd6000)

libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb6dc3000)

libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb6d9b000)


Perhaps there are intermediate dependencies missing from hidraw?
Darryl
