### ISSUE TITLE
please tag a first version

### ISSUE THREAD

**Issue by jandd** [darrylb123/usbrelay#7]
Hello again,

would you mind tagging the current HEAD as version 0.1? I think the code is good and works quite well.

Best regards
Jan

**Comment by darrylb123** [comment]
Hello,
I have just released 0.4 of usbrelay which adds the ability to change the device serial number. Many devices are being sold with duplicate serial numbers.

**Comment by darrylb123** [comment]
Hello,
A Python interface has been added to the 0.5 release. The Python interface required usbrelay to be split into a library and binary with an additional library for the python interface. The documentation shows how to build both.
