### ISSUE TITLE
Help! Seems USBRelay's serial is missing

### ISSUE THREAD

**Issue by dracedj** [darrylb123/usbrelay#74]
Hi! Ive got the 8 ch relay worked, but since yesterday it seems it lost its serial which is needed to operate.
When i try with the GUI on a windows computer it shows as serial just: ","

Any idea how to fix this?

**Comment by darrylb123** [comment]
Have a look at the documentation about changing the serial.
You can refer to it by it's device path when changing the serial.

Change the serial permanently

Use the fictitious relay 0 to set the serial permanently. If you have
duplicate serials, make sure only one is plugged in when you change it.
Maximum of 5 character serial. It is probably sensible to change one module
at a time to avoid serial collisions. You may also use the device path to
set the serial as above

$ sudo usbrelay
ZXCV_1=0
ZXCV_2=0

$ sudo usbrelay /dev/hidraw4_0=ZAQ12
ZXCV_1=0
ZXCV_2=0
Setting new serial

$ sudo usbrelay
ZAQ12_1=0
ZAQ12_2=0
