### ISSUE TITLE
Cross compiling for OpenWRT

### ISSUE THREAD

**Issue by jabss** [darrylb123/usbrelay#8]
Hello Darrylb,

This is not really a problem, but I couldn't find any other way to contact you...
Fist of all, I'd like to say many thanks for this program, it is really useful!  I mean, how cool can it be to turn on/off stuff from the computer?? :)

I have compiled your code in ubuntu 64 and Rasperry PI and it works great! 

Now I'd like to have it also in my router (based on OpenWRT), so I have to cross-compile it.
I have built the cross-compile environment and I was able to compile a simple "hello world" program (tested successfully, so I guess we can say the build environment is OK). 
However, I'm not able to cross-compile your code because I'm unable to link the HIDAPI libraries. Do I need to cross-compile the HIDAPI libraries in advance or its code is enough to cross-compile usbrelay.c ?
Maybe this is a very basic question, but I'm not a programmer or anything and I'm struggling with this for a couple of months...

The error I'm getting is:
[code]
/mnt/storage/usbrelay-openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/bin/mips-openwrt-linux-gcc -o usbrelay usbrelay.c -lhidapi-hidraw

/mnt/storage/usbrelay-openwrt/openwrt/staging_dir/toolchain-mips_34kc_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/mips-openwrt-linux-uclibc/4.8.3/../../../../mips-openwrt-linux-uclibc/bin/ld: cannot find -lhidapi-hidraw
collect2: error: ld returned 1 exit status
[/code]

I have created a post in openwrt forum, but I'm afraid I couldn't get an answer I could understand...
More info on https://forum.openwrt.org/viewtopic.php?id=50682

Would you know what would the problem be and if so, would you point me in the right direction?

Thank you very much,
João Silva

**Comment by ryzhovau** [comment]
@jabss, you may take a look [here](https://github.com/Entware-ng/rtndev/blob/master/usbrelay/Makefile).

@darrylb123, thanks for `usbrelay`. Now it's included into Entware-ng repo.
