### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by joshuar87** [darrylb123/usbrelay#82]
Hi guys,

Library working well for about a week and then get issue with no devices found. Reinstall, change usb port. Worked briefly and now get:
ioctl (GFEATURE): Broken pipe
hid_get_feature_report
: Broken pipe

Using Linux mint 20.2

**Comment by joshuar87** [comment]
So after working briefly it goes back to:
libusbrelay: 0.9-26-g1476a27ec6
usbrelay: 0.9-26-g1476a27ec6
enumerate_relay_boards()Found 0 devices

**Comment by darrylb123** [comment]
Try lsusb before and when it stops working.
Probably disappearing.
Cable or relay hardware.
