### ISSUE TITLE
intermittent hid_get_feature_report: Protocol error

### ISSUE THREAD

**Issue by toby11** [darrylb123/usbrelay#88]
usbrelay is working fine 99% of the time for me but I did have it fail once the other day with protocol error - it worked fine a few minutes later, any idea what causes this? Do you have any retry functionality build into the code? 

I will handle it in my bash script and retry myself for the time being. are you returning a non-zero exit code on error?

usbrelay output
Orig: 6QMBS, Serial: 6QMBS, Relay: 3 State: ff
Device Found
  type: 16c0 05df
  path: /dev/hidraw1
  serial_number:
  Manufacturer: www.dcttech.com
  Product:      USBRelay8
  Release:      100
  Interface:    0
  Number of Relays = 8
ioctl (GFEATURE): Protocol error
hid_get_feature_report: Protocol error

lsusb output
Bus 003 Device 004: ID 16c0:05df Van Ooijen Technische Informatica HID device except mice, keyboards, and joysticks

**Comment by darrylb123** [comment]
Hi there,
I'd be checking hardware in a situation like this. Intermittent errors can
be a pain.
Try a different cable for a while...

Darryl
