### ISSUE TITLE
Using the Python Extensions in Windows

### ISSUE THREAD

**Issue by williamblair333** [darrylb123/usbrelay#93]
I'm certain I'm being ignorant - but I had to ask:  Can the python extensions of usbrelay be exported and used in Windows?  Apologies for posting here as I didn't know where else to ask.  Thanks.

**Comment by wentasah** [comment]
> I'm certain I'm being ignorant - but I had to ask: Can the python
> extensions of usbrelay be exported and used in Windows?

I guess it's theoretically possible, but it will need some work. We use
the hidapi library, which should work on Windows, but I don't think that
our code has ever be compiled for Windows. We probably have few Linux
specific things in our code and if somebody replaces them with platform
independent code, it might work.

If time allows, I might look into this eventually.

**Comment by darrylb123** [comment]
I had a quick look at mingw and cross compiling, looks like it's doable for
the command line tool and library. The python extension is another matter.

**Comment by williamblair333** [comment]
I may not be useful, but, what can someone do to assist?

**Comment by darrylb123** [comment]
No. The python extension is a wrapper around libusbrelay.

I need to find someone that uses/develops on windows to add the required
code for windows.

Darryl
