### ISSUE TITLE
Fedora repository

### ISSUE THREAD

**Issue by aldogig** [darrylb123/usbrelay#96]
In the initial page 
[https://github.com/darrylb123/usbrelay](https://github.com/darrylb123/usbrelay)
you say that for Fedora it is possible to issue the command:
_**$ sudo dnf install usbrelay-common python3-usbrelay usbrelay-mqtt**_
However I get no result. 
I believe a repository shall be first added.
Can you state, as well, in which repository can be found the above packages?
Many thanks 
Aldo

**Comment by darrylb123** [comment]
Yes, we are still working on getting the packages in the Fedora
repositories.
They are currently under review. The test build packages are here.
https://copr.fedorainfracloud.org/coprs/fuller/usbrelay/build/5073353/

Darryl

**Comment by darrylb123** [comment]
Currently in updates-testing. Should be in main repository in a day or 2

**Comment by aldogig** [comment]
Many thanks.
