### ISSUE TITLE
Python get relay status?

### ISSUE THREAD

**Issue by durian** [darrylb123/usbrelay#98]
Is it possible to get the status of a single relay from the Python module? The board_control() function only seems to be able to switch a relay on or off, and I did not find another function in the Python code.

**Comment by darrylb123** [comment]
The function board_details() returns an array of the modules and the state
of each module. The state is returned as an integer of all relays.
Have a look at the tests/usbrelay_tests.py for an example

Darryl

**Comment by durian** [comment]
Yes, thanks, that will work!
